/**
 */

tinyMCE.addI18n('fr.xoopsimagemanager_dlg',{
tab_general:"G\u00E9n\u00E9ral",
tab_appearance:"Apparence",
tab_advanced:"Avanc\u00E9",
general:"G\u00E9n\u00E9ral",
title:"Titre",
preview:"Pr\u00E9visualiser",
constrain_proportions:"Conserver les proportions",
langdir:"Sens de lecture",
langcode:"Code de la langue",
long_desc:"Description longue du lien",
style:"Style",
classes:"Classes",
ltr:"De gauche \u00e0 droite",
rtl:"De droite \u00e0 gauche",
id:"Id",
map:"Carte image",
swap_image:"Alterner image",
alt_image:"Image alternative",
mouseover:"au passage de la souris",
mouseout:"\u00e0 la sortie de la souris",
misc:"Divers",
example_img:"Apparence aper\u00e7u image",
missing_alt:"\u00cates-vous s\u00fbr de vouloir continuer sans inclure une description de l\'image ? Sans cette description, l\'image peut ne pas \u00eatre accessible \u00e0 certains utilisateurs moins valides, ou \u00e0 ceux qui utilisent un navigateur texte, ou qui naviguent sur internet avec les images d\u00e9sactiv\u00e9es.",
dialog_title:"Explorateur d\'images Xoops",
src:"Lien de l\'image",
alt:"Description de l\'image",
list:"Liste d\'images",
border:"Bordure",
dimensions:"Dimensions",
vspace:"Espacement vertical",
hspace:"Espacement horizontal",
align:"Alignement",
align_baseline:"Base",
align_top:"Haut",
align_middle:"Milieu",
align_bottom:"Bas",
align_texttop:"Haut du texte",
align_textbottom:"Bas du texte",
align_left:"Gauche",
align_right:"Droite",
image_list:"Liste d\'images"
});

tinyMCE.addI18n('fr.xoopsimagebrowser_dlg',{
dialog_title:"Navigateur d\'images Xoops",
tab_listimages:"Images",
tab_loadimage:"Ajouter une image",
tab_listcategories:"Cat\u00e9gories",
tab_createcategory:"Ajouter une cat\u00e9gorie",
select_image: "cliquez sur l\'image pour la s\u00e9lectionner"
});